#!/usr/bin/env python3
# ROM assets for the Vita / PC port.
#
# The port does not ship the game's graphics, sounds and map data: those are
# built as same-size placeholders (an 8 byte marker + zeros) and filled in at
# startup from the player's own Emerald Rogue ROM (src/platform/rom_assets.c).
#
# This tool, run once by a developer with an official ROM and a built tree
# (the generated .4bpp/.lz/.bin files must exist), writes:
#   tools/pc/rom_assets_strip.txt    "<id> <path>" of every asset file to strip
#   src/platform/rom_assets_table.c  id -> offset/size in the ROM, ROM SHA-1
# Both only contain numbers and file names, never ROM data.
#
# usage: tools/pc/rom_assets.py <official ROM>
import glob, hashlib, os, re, sys, zlib

MARKER_SIZE = 8

def referenced_assets():
    files = set()
    c_re = re.compile(r'INCBIN_[SU](?:8|16|32)\(([^)]*)\)')
    for f in glob.glob('src/**/*.[ch]', recursive=True) + glob.glob('include/**/*.h', recursive=True):
        for m in c_re.finditer(open(f, errors='replace').read()):
            files.update(re.findall(r'"([^"]+)"', m.group(1)))
    s_re = re.compile(r'^\s*\.incbin\s+"([^"]+)"', re.M)
    for pattern in ('data/**/*.s', 'data/**/*.inc', 'sound/**/*.s', 'sound/**/*.inc', 'asm/**/*.s'):
        for f in glob.glob(pattern, recursive=True):
            files.update(s_re.findall(open(f, errors='replace').read()))
    return sorted(files)

def main():
    os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
    rom = open(sys.argv[1], 'rb').read()
    sha1 = hashlib.sha1(rom).digest()

    strip, table, ids = [], [], {}
    not_built = not_in_rom = tiny = 0
    for path in referenced_assets():
        if not os.path.exists(path):
            not_built += 1          # not used by this build
            continue
        data = open(path, 'rb').read()
        if len(data) < MARKER_SIZE:
            tiny += 1               # too small for a marker: stays embedded
            continue
        aid = zlib.crc32(path.encode()) & 0xFFFFFFFF
        if aid in ids:
            sys.exit('id collision: %s / %s' % (path, ids[aid]))
        ids[aid] = path
        strip.append((aid, path))
        off = rom.find(data)
        if off < 0:
            not_in_rom += 1         # not in the official ROM (unused there): stays zero
            continue
        table.append((aid, off, len(data)))

    with open('tools/pc/rom_assets_strip.txt', 'w') as f:
        f.write('# generated by tools/pc/rom_assets.py: asset files replaced by placeholders\n')
        for aid, path in strip:
            f.write('%08x %s\n' % (aid, path))

    table.sort()
    with open('src/platform/rom_assets_table.c', 'w') as f:
        f.write('// generated by tools/pc/rom_assets.py: where each asset lives in the\n')
        f.write('// official ROM (offsets and sizes only, no ROM data)\n')
        f.write('#include "platform/rom_assets.h"\n\n')
        f.write('const unsigned char gRomAssetsSha1[20] = {%s};\n' % ','.join('0x%02x' % b for b in sha1))
        f.write('const unsigned int gRomAssetsRomSize = %d;\n' % len(rom))
        f.write('const unsigned int gRomAssetsCount = %d;\n' % len(table))
        f.write('const struct RomAsset gRomAssets[] = {\n')
        for aid, off, size in table:
            f.write('    {0x%08x, 0x%07x, %d},\n' % (aid, off, size))
        f.write('};\n')

    print('assets stripped: %d, found in the ROM: %d (%.1f MB), not in the ROM: %d, too small (kept): %d, not built: %d'
          % (len(strip), len(table), sum(t[2] for t in table) / 1e6, not_in_rom, tiny, not_built))
    print('ROM SHA-1 %s' % sha1.hex())

if __name__ == '__main__':
    main()
