#!/usr/bin/env python3
# Generates src/data/showdown_names.h: the Pokemon Showdown spelling of every
# species, move, item, ability and nature, indexed by the game's constants, so
# the party export (src/showdown_export.c) imports into the Showdown damage
# calculator, which matches names exactly. The game's own names are shortened
# ("DublIronBash") and don't tell forms apart.
#
# usage: tools/pc/showdown_names.py <damage-calc data dir>
#   the data dir holds species.ts, moves.ts, items.ts, abilities.ts, natures.ts
#   from https://github.com/smogon/damage-calc/tree/master/calc/src/data
import os, re, sys, unicodedata

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
data = sys.argv[1]

def to_id(s):
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode()  # Flabébé -> Flabebe
    return re.sub(r'[^a-z0-9]', '', s.lower())

# a quoted TypeScript string, with escapes ('King\'s Shield', "Farfetch’d")
QUOTED = r"""'((?:[^'\\]|\\.)*)'|"((?:[^"\\]|\\.)*)\""""

def unquote(s):
    s = re.sub(r'\\u([0-9a-fA-F]{4})', lambda m: chr(int(m.group(1), 16)), s)
    return re.sub(r'\\(.)', r'\1', s)

def calc_names(name, keyed):
    text = open(os.path.join(data, name + '.ts'), encoding='utf-8').read()
    if keyed:  # object keys: "  Bulbasaur: {" / "  'Mr. Mime': {"
        # (an unquoted key can hold combining accents: "Flabébé")
        found = re.findall(r"^\s{2}(?:%s|([^\s:'\"]+)):\s*\{" % QUOTED, text, re.M)
        names = [unquote(a or b or c) for a, b, c in found]
    else:      # string arrays: "  'Choice Band',"
        names = [unquote(a or b) for a, b in re.findall(r"^\s+(?:%s),?\s*$" % QUOTED, text, re.M)]
    out = {}
    for n in names:
        out.setdefault(to_id(n), n)
    return out

def constants(header, prefix, skip):
    text = open(os.path.join(root, 'include', 'constants', header), encoding='latin-1').read()
    out = []
    for name, value in re.findall(r'^#define (%s\w+)\s+(.+?)\s*(?://.*)?$' % prefix, text, re.M):
        if name in skip or re.fullmatch(r'%s\w+' % prefix, value.strip('() ')):
            continue  # counts and aliases of other constants
        out.append(name)
    return out

# the game's form suffixes that Showdown writes differently
SPECIES_FIXES = [('GIGANTAMAX', 'GMAX'), ('ALOLAN', 'ALOLA'), ('GALARIAN', 'GALAR'), ('HISUIAN', 'HISUI'),
                 ('PALDEAN', 'PALDEA'), ('_FEMALE', '_F'), ('_MALE', '')]

def match(const, prefix, names, fixes=(), base_fallback=False):
    suffix = const[len(prefix):]
    for a, b in fixes:
        suffix = suffix.replace(a, b)
    parts = suffix.split('_')
    while parts:
        hit = names.get(to_id(''.join(parts)))
        if hit:
            return hit
        if not base_fallback:
            return None
        parts = parts[:-1]  # unknown form: fall back to the base species
    return None

def table(f, ctype, name, count, consts, prefix, names, **kw):
    hits = 0
    f.write('const char *const %s[%s] =\n{\n' % (name, count))
    for c in consts:
        n = match(c, prefix, names, **kw)
        if n:
            hits += 1
            f.write('    [%s] = "%s",\n' % (c, n.replace('\\', '\\\\').replace('"', '\\"')))
    f.write('};\n\n')
    print('%-28s %d of %d names' % (name, hits, len(consts)))

species = calc_names('species', True)
moves = calc_names('moves', True)
items = calc_names('items', False)
abilities = calc_names('abilities', False)
abilities['asoneicerider'] = 'As One (Glastrier)'
abilities['asoneshadowrider'] = 'As One (Spectrier)'
# natures are one plain word each (natures.ts is "Adamant: ['atk', 'spa']")
natures = {to_id(c[7:]): c[7:].title() for c in constants('pokemon.h', 'NATURE_', set())}

out = os.path.join(root, 'src', 'data', 'showdown_names.h')
with open(out, 'w') as f:
    f.write('// Generated by tools/pc/showdown_names.py from the Showdown damage calculator data - do not edit\n\n')
    table(f, 'species', 'gShowdownSpeciesNames', 'NUM_SPECIES',
          constants('species.h', 'SPECIES_', {'SPECIES_NONE', 'SPECIES_EGG', 'SPECIES_SHINY_TAG'}),
          'SPECIES_', species, fixes=SPECIES_FIXES, base_fallback=True)
    table(f, 'moves', 'gShowdownMoveNames', 'MOVES_COUNT_ALL', constants('moves.h', 'MOVE_', {'MOVE_NONE'}), 'MOVE_', moves)
    table(f, 'items', 'gShowdownItemNames', 'ITEMS_COUNT', constants('items.h', 'ITEM_', {'ITEM_NONE'}), 'ITEM_', items)
    table(f, 'abilities', 'gShowdownAbilityNames', 'ABILITIES_COUNT',
          constants('abilities.h', 'ABILITY_', {'ABILITY_NONE'}), 'ABILITY_', abilities)
    table(f, 'natures', 'gShowdownNatureNames', 'NUM_NATURES', constants('pokemon.h', 'NATURE_', set()), 'NATURE_', natures)
print('wrote', out)
