// Loads the game's graphics, sounds and map data from the player's own ROM.
//
// ROM_ASSETS builds replace every embedded asset file with a placeholder of
// the same size: an 8 byte marker ("\x7fRAS" + little endian id) and zeros
// (tools/preproc for C INCBINs, tools/pc/asmfilter.py for .incbin). The game's
// data sections are writable in these builds (Makefile PRELINK), so at startup
// every marker is replaced by the asset's bytes from the ROM, located through
// src/platform/rom_assets_table.c (generated by tools/pc/rom_assets.py).
#include <dirent.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "platform/rom_assets.h"

extern void PlatformLog(const char *fmt, ...);

#ifdef ROM_ASSETS

extern unsigned char __start_gamerodata[], __stop_gamerodata[];
extern unsigned char __start_gamedata[], __stop_gamedata[];

// ---- SHA-1 -------------------------------------------------------------------

struct Sha1
{
    uint32_t h[5];
    uint64_t length;
    uint8_t block[64];
    uint32_t used;
};

#define ROL(x, n) (((x) << (n)) | ((x) >> (32 - (n))))

static void Sha1Block(struct Sha1 *s, const uint8_t *p)
{
    uint32_t w[80], a, b, c, d, e, f, k, t;
    int i;

    for (i = 0; i < 16; i++)
        w[i] = (uint32_t)p[i * 4] << 24 | (uint32_t)p[i * 4 + 1] << 16 | (uint32_t)p[i * 4 + 2] << 8 | p[i * 4 + 3];
    for (; i < 80; i++)
        w[i] = ROL(w[i - 3] ^ w[i - 8] ^ w[i - 14] ^ w[i - 16], 1);
    a = s->h[0]; b = s->h[1]; c = s->h[2]; d = s->h[3]; e = s->h[4];
    for (i = 0; i < 80; i++)
    {
        if (i < 20)      { f = (b & c) | (~b & d);          k = 0x5A827999; }
        else if (i < 40) { f = b ^ c ^ d;                   k = 0x6ED9EBA1; }
        else if (i < 60) { f = (b & c) | (b & d) | (c & d); k = 0x8F1BBCDC; }
        else             { f = b ^ c ^ d;                   k = 0xCA62C1D6; }
        t = ROL(a, 5) + f + e + k + w[i];
        e = d; d = c; c = ROL(b, 30); b = a; a = t;
    }
    s->h[0] += a; s->h[1] += b; s->h[2] += c; s->h[3] += d; s->h[4] += e;
}

static void Sha1(const uint8_t *data, size_t len, uint8_t out[20])
{
    struct Sha1 s = { { 0x67452301, 0xEFCDAB89, 0x98BADCFE, 0x10325476, 0xC3D2E1F0 }, 0, { 0 }, 0 };
    size_t i;
    uint8_t pad[72] = { 0x80 };
    uint64_t bits = (uint64_t)len * 8;
    size_t padLen;

    for (i = 0; i + 64 <= len; i += 64)
        Sha1Block(&s, data + i);
    memcpy(s.block, data + i, len - i);
    s.used = len - i;
    padLen = (s.used < 56) ? 56 - s.used : 120 - s.used;
    for (i = 0; i < 8; i++)
        pad[padLen + i] = bits >> (56 - 8 * i);
    for (i = 0; i < padLen + 8; i++)
    {
        s.block[s.used++] = pad[i];
        if (s.used == 64)
        {
            Sha1Block(&s, s.block);
            s.used = 0;
        }
    }
    for (i = 0; i < 20; i++)
        out[i] = s.h[i / 4] >> (24 - 8 * (i % 4));
}

// ---- loading -----------------------------------------------------------------

static const struct RomAsset *FindAsset(uint32_t id)
{
    unsigned int lo = 0, hi = gRomAssetsCount;
    while (lo < hi)
    {
        unsigned int mid = (lo + hi) / 2;
        if (gRomAssets[mid].id < id)
            lo = mid + 1;
        else
            hi = mid;
    }
    return (lo < gRomAssetsCount && gRomAssets[lo].id == id) ? &gRomAssets[lo] : NULL;
}

// Replaces every marker in [start, end) with the asset bytes; returns how many
static unsigned int PatchSection(unsigned char *start, unsigned char *end, const uint8_t *rom, unsigned int *unknown)
{
    unsigned int patched = 0;
    unsigned char *p = start;

    while (p + 8 <= end)
    {
        const struct RomAsset *asset;
        uint32_t id;

        p = memchr(p, 0x7F, end - p - 7);
        if (p == NULL)
            break;
        if (p[1] != 'R' || p[2] != 'A' || p[3] != 'S')
        {
            p++;
            continue;
        }
        id = p[4] | p[5] << 8 | p[6] << 16 | (uint32_t)p[7] << 24;
        asset = FindAsset(id);
        if (asset == NULL || p + asset->size > end)
        {
            // an asset the official ROM doesn't have (unused there), or a
            // coincidental match: leave it
            (*unknown)++;
            p++;
            continue;
        }
        memcpy(p, rom + asset->offset, asset->size);
        patched++;
        p += asset->size;
    }
    return patched;
}

static uint8_t *ReadRom(const char *path)
{
    FILE *f = fopen(path, "rb");
    uint8_t *rom;
    long size;

    if (f == NULL)
        return NULL;
    fseek(f, 0, SEEK_END);
    size = ftell(f);
    if (size != (long)gRomAssetsRomSize)
    {
        fclose(f);
        return NULL;
    }
    fseek(f, 0, SEEK_SET);
    rom = malloc(size);
    if (rom != NULL && fread(rom, 1, size, f) != (size_t)size)
    {
        free(rom);
        rom = NULL;
    }
    fclose(f);
    return rom;
}

bool RomAssets_Load(const char *dataDir, char *err, size_t errSize)
{
    DIR *dir = opendir(dataDir);
    struct dirent *entry;
    uint8_t *rom = NULL;
    char path[512];
    bool wrongVersion = false;

    // any .gba file in the data folder
    while (dir != NULL && rom == NULL && (entry = readdir(dir)) != NULL)
    {
        size_t len = strlen(entry->d_name);
        uint8_t sha1[20];

        if (len < 4 || strcmp(entry->d_name + len - 4, ".gba") != 0)
            continue;
        snprintf(path, sizeof(path), "%s%s", dataDir, entry->d_name);
        rom = ReadRom(path);
        if (rom == NULL)
        {
            wrongVersion = true;
            continue;
        }
        Sha1(rom, gRomAssetsRomSize, sha1);
        if (memcmp(sha1, gRomAssetsSha1, 20) != 0)
        {
            PlatformLog("%s: not the supported ROM version\n", path);
            free(rom);
            rom = NULL;
            wrongVersion = true;
        }
    }
    if (dir != NULL)
        closedir(dir);
    if (rom == NULL)
    {
        snprintf(err, errSize, wrongVersion ? "wrong ROM version" : "no ROM found");
        return false;
    }

    {
        unsigned int unknown = 0;
        unsigned int n = PatchSection(__start_gamerodata, __stop_gamerodata, rom, &unknown)
                       + PatchSection(__start_gamedata, __stop_gamedata, rom, &unknown);
        PlatformLog("ROM assets: %u loaded from %s (%u of %u table entries, %u markers unused)\n",
                    n, path, n, gRomAssetsCount, unknown);
    }
    free(rom);
    return true;
}

#else // !ROM_ASSETS: assets are embedded

bool RomAssets_Load(const char *dataDir, char *err, size_t errSize)
{
    (void)dataDir;
    (void)err;
    (void)errSize;
    return true;
}

#endif
